# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Passed as always :)"

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: | 
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fill .env file
        run: echo "NEXT_PUBLIC_GITHUB_API_KEY=${{ secrets.NEXT_PUBLIC_GITHUB_API_KEY }}" > .env

      - run: yarn install --frozen-lockfile
      - run: yarn run build

      - name: Share static build files
        uses: actions/upload-artifact@v4
        with:
          name: static-folder
          path: .next/static

      - name: Share standalone build files
        uses: actions/upload-artifact@v4
        with:
          name: standalone-folder
          include-hidden-files: 'true'
          path: .next/standalone


  upload_static:
    name: Upload static files to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download static files from previous job
        uses: actions/download-artifact@v4
        with:
          name: static-folder
          path: .next/static

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload static built files to S3
        run: aws s3 sync --delete .next/static s3://${{ secrets.AWS_S3_STATIC_FILES_NAME }}/.next/static

      - name: Upload static media files to S3
        run: aws s3 sync --delete public s3://${{ secrets.AWS_S3_STATIC_FILES_NAME }}/public


  upload_standalone:
    name: Zip standalone files and upload to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download standalone files from previous job
        uses: actions/download-artifact@v4
        with:
          name: standalone-folder
          path: .next/standalone

      - name: Zip standalone files
        run: cd .next/standalone && zip -r code.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload standalone built files to S3
        run: aws s3 cp .next/standalone/code.zip s3://${{ secrets.AWS_S3_STATIC_FILES_NAME }}/code.zip