# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Share static build files
        uses: actions/upload-artifact@v4
        with:
          name: static-folder
          path: .next/standalone

  upload_static:
    name: Upload static files to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download static files from previous job
        uses: actions/download-artifact@v4
        with:
          name: static-folder
          path: .next/standalone
      - run: ls -la
      - run: cd .next/standalone && ls -la
      - name: Upload static files to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
          source_dir: '.next/standalone'
          destination_dir: '/nextjs'


