# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Passed as always :)"

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fill .env file
        run: echo "NEXT_PUBLIC_GITHUB_API_KEY=${{ secrets.NEXT_PUBLIC_GITHUB_API_KEY }}" > .env

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Share static build files
        uses: actions/upload-artifact@v4
        with:
          name: static-folder
          path: .next/standalone

  upload_static:
    name: Upload static files to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download static files from previous job
        uses: actions/download-artifact@v4
        with:
          name: static-folder
          path: .next/standalone

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload static built files to S3
        run: aws s3 sync --delete .next/standalone s3://${{ secrets.AWS_BUCKET_NAME }}

      - name: Upload static media files to S3
        run: aws s3 sync --delete public s3://${{ secrets.AWS_BUCKET_NAME }}/public


